spring:
  application:
    name: jobhunter
  datasource:
    url: ${RAILWAY_MYSQL_URL}
    username: ${RAILWAY_MYSQL_USERNAME}
    password: ${RAILWAY_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

jwt:
  base64-secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400

vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  url: ${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  returnUrl: ${VNPAY_RETURN_URL:https://be-jobit.onrender.com/api/v1/payments/vnpay-callback}
  frontendUrl: ${FRONTEND_URL:https://hsjobit.onrender.com}

logging:
  level:
    root: INFO
    com.jobhunter: INFO 