spring:
  application:
    name: jobhunter
  datasource:
    url: ${RAILWAY_MYSQL_URL}
    username: ${RAILWAY_MYSQL_USERNAME}
    password: ${RAILWAY_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,db
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    db:
      enabled: true

jwt:
  base64-secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 8640000
  refresh-token-validity-in-seconds: 8640000

vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  url: ${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  returnUrl: ${VNPAY_RETURN_URL:https://be-jobit.onrender.com/api/v1/payments/vnpay-callback}
  frontendUrl: ${FRONTEND_URL:https://hsjobit.onrender.com}

logging:
  level:
    root: INFO
    com.jobhunter: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: TRACE
    com.zaxxer.hikari: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.boot.actuate: DEBUG 